#!/usr/bin/env bash
# shellcheck disable=SC1090,SC1091,SC2034

LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BASE_COMMAND="$(basename "${BASH_SOURCE[0]}")"

source "${LOCATION}"/subcommand_tools.sh
